name: Test-integration - Build - Test - Deliver

on:
  push:
    branches:
      - 'ready/**' 
jobs:
  integrate:
    name: Integrate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: fetch
      run: |
          git fetch --prune --unshallow
    - name: Setting var
      id: currentbranch
      run: echo ::set-output name=name::$(git branch | grep \* | cut -d ' ' -f2-)

    - name: setting git config
      run: git config --global user.email "robot@hello.com"
 
    - name: setting git config
      run: git config --global user.name "Robot"

    - name: Rebase to remote branch
      run: git rebase

    - name: Checkout target branch
      run: git checkout master

    - name: Pull latest
      run: git pull origin master

    - name: Merge
      run: git merge --ff-only

    - name: Install dependencies
      run: |
        go get -v -d ./...
    - name: Build
      run: go build -v .

    - name: test
      run: |
        echo $GOBIN
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/onsi/ginkgo/ginkgo
        ginkgo -r -v --trace

    - name: Push to master
      run: git push